create table if not exists directors (
    id bigint generated by default as identity primary key,
    name nvarchar(255)
);
create table if not exists genres (
    id bigint primary key,
    name nvarchar(255)
);
create table if not exists mpa (
    id bigint primary key,
    name nvarchar(255),
    description nvarchar(255)
);
create table if not exists films (
    id bigint generated by default as identity primary key,
    name nvarchar(255),
    description nvarchar(255),
    release_date date,
    duration integer,
    mpa bigint,
    foreign key (mpa) references mpa(id)
);
create table if not exists users (
    id bigint generated by default as identity primary key,
    name nvarchar(255),
    email nvarchar(255),
    login nvarchar(255),
    birthday date
);
create table if not exists friendship (
    user_id bigint,
    friend_id bigint,
    accepted boolean default false,
    foreign key (user_id) references users(id),
    foreign key (friend_id) references users(id)
);
create table if not exists likes (
    user_id bigint,
    film_id bigint,
    foreign key (user_id) references users(id),
    foreign key (film_id) references films(id)
);
create table if not exists film_genre (
    film_id bigint,
    genre_id bigint,
    foreign key (film_id) references films(id),
    foreign key (genre_id) references genres(id)
);
create table if not exists film_director (
    film_id bigint,
    director_id bigint,
    foreign key (film_id) references films(id),
    foreign key (director_id) references directors(id)
);
create table if not exists reviews (
    id bigint generated by default as identity primary key,
    user_id bigint,
    film_id bigint,
    content nvarchar(2048),
    is_positive boolean,
    useful integer default 0,
    foreign key (user_id) references users(id),
    foreign key (film_id) references films(id)
);
create table if not exists review_user (
    review_id bigint,
    user_id bigint,
    val integer,
    foreign key (review_id) references reviews(id),
    foreign key (user_id) references users(id)
);
create table if not exists feed (
    event_id bigint generated by default as identity primary key,
    timestamp bigint,
    user_id bigint,
    event_type nvarchar(64),
    operation nvarchar(64),
    entity_id bigint,
    foreign key (user_id) references users(id)
);